const KEY='adab_students_demo_v2', SESSION='adab_student_session_v2', CLOUD='adab_cloud_student_token_v1', NOTICES='adab_notices_demo_v2';
const API_BASE='/api';
const IS_PUBLISHED=location.protocol==='https:'&&!/^(localhost|127\.0\.0\.1)$/.test(location.hostname);
let CLOUD_STUDENT=null;
const $=id=>document.getElementById(id), modal=$('accountModal'); let mode='login';
const axes=['شعر الحماسة','المنزع العقلي','رسالة الغفران','مغامرة رأس المملوك جابر','حدث أبو هريرة قال'];
function missionContentPath(id){const m=String(id||'').match(/^(lessons|training|research)-(\d+)-(\d+)$/); if(!m)return 'lessons__index.html'; const dir=m[1],prefix=dir==='lessons'?'lesson':dir; return `${dir==='lessons'?'lessons__':dir==='training'?'training__':'research__'}${prefix}-${m[2]}-${m[3]}.html`;}
function students(){const local=JSON.parse(localStorage.getItem(KEY)||'[]'); if(CLOUD_STUDENT){const i=local.findIndex(x=>String(x.id)===String(CLOUD_STUDENT.id)); if(i>=0)local[i]={...local[i],...CLOUD_STUDENT}; else local.push(CLOUD_STUDENT); localStorage.setItem(KEY,JSON.stringify(local));} return local}
function notices(){return JSON.parse(localStorage.getItem(NOTICES)||'[]')}
function targetMatch(n,u){return n.target==='all'||n.target===u.status||n.target===('student:'+u.id)}
function renderNotices(u){const box=$('studentNoticeList');if(!box)return;const ns=notices().filter(n=>targetMatch(n,u)).slice(-6).reverse();box.innerHTML=ns.length?ns.map(n=>`<div class="student-notice-item"><b>${n.typeLabel||'تنبيه'}</b><h3>${n.title}</h3><p>${n.text}</p><small>${n.date||''}</small>${n.contentId?`<a href="${n.contentId.startsWith('lessons-')?'lessons__':n.contentId.startsWith('research-')?'research__':'training__'}${n.contentId.startsWith('lessons-')?'lesson-':n.contentId.startsWith('research-')?'research-':'training-'}${n.contentId.split('-').slice(-2).join('-')}.html">فتح المحتوى ←</a>`:''}</div>`).join(''):'<div class="muted">لا توجد إعلانات جديدة.</div>'}
function saveStudents(v){localStorage.setItem(KEY,JSON.stringify(v))}
function current(){const phone=sessionStorage.getItem(SESSION); const local=students(); return CLOUD_STUDENT||local.find(s=>s.phone===phone)}
async function cloudJson(path,opts={}){const headers={'content-type':'application/json',...(opts.headers||{})};const token=sessionStorage.getItem(CLOUD);if(token)headers.authorization='Bearer '+token;const r=await fetch(API_BASE+path,{...opts,headers});let d={};try{d=await r.json()}catch{}if(!r.ok){const err=new Error(d.error||'تعذر الاتصال بالخادم');err.detail=d.detail||'';throw err}return d}
async function hydrateCloud(){const token=sessionStorage.getItem(CLOUD);if(!token)return false;try{const d=await cloudJson('/me');CLOUD_STUDENT=d.student;localStorage.setItem(KEY,JSON.stringify([CLOUD_STUDENT]));sessionStorage.setItem(SESSION,CLOUD_STUDENT.phone);return true}catch(e){return false}}
function statusLabel(s){return ({new:'مستخدم جديد',active:'مستخدم فعليّ',verified:'مستخدم موثّق',suspended:'موقوف'})[s]||'مستخدم جديد'}
function openModal(next='login'){mode=next; modal.hidden=false; document.body.classList.add('modal-open'); $('modalTitle').textContent=next==='signup'?'إنشاء حساب جديد':'تسجيل الدخول'; $('modalIntro').textContent=next==='signup'?'أنشئ حسابك، ثم ينتظر حسابك التوثيق من الأستاذ.':'أدخل رقم الهاتف وكلمة العبور للدخول إلى فضائك.'; $('nameField').hidden=next!=='signup'; $('schoolField').hidden=next!=='signup'; $('formSubmit').textContent=next==='signup'?'إنشاء الحساب':'دخول'; $('passwordInput').required=true; $('formFeedback').textContent='';}
function close(){modal.hidden=true;document.body.classList.remove('modal-open');$('passwordInput').required=true}
function renderMissionWorkspace(u){const m=u.mission||{};const status=m.status||'new';const title=$('workspaceMissionTitle'),text=$('workspaceMissionText'),link=$('workspaceContentLink'),pill=$('missionStatus'),form=$('missionSubmissionForm'),area=$('missionSubmission'),feedback=$('missionSubmissionFeedback'),review=$('missionReview'),submit=$('submitMission');if(!title)return;title.textContent=m.assigned?m.title:'لا توجد مهمة مسندة حاليًا';text.textContent=m.assigned?m.text:'عندما يسند إليك الأستاذ مهمة ستظهر هنا تعليماتها والمحتوى المرتبط بها.';if(m.contentId){link.href=missionContentPath(m.contentId);link.style.display='inline-block'}else{link.removeAttribute('href');link.style.display='none'}const labels={new:'مهمة جديدة',pending:'في انتظار الإنجاز',submitted:'أرسلته — في انتظار مراجعة الأستاذ',reviewed:'تمت مراجعة الإنجاز'};pill.textContent=labels[status]||'مهمة جارية';pill.className='status-pill '+(status==='reviewed'?'verified':status==='submitted'?'active':'');area.value=m.submission?.text||'';feedback.textContent='';submit.disabled=!m.assigned||status==='submitted'||status==='reviewed';submit.textContent=status==='submitted'?'تم إرسال الإنجاز':status==='reviewed'?'تمت المراجعة':'إرسال الإنجاز إلى الأستاذ';if(m.review?.feedback){review.hidden=false;review.innerHTML=`<h3>ملاحظة الأستاذ</h3><p>${m.review.feedback}</p><small>${m.review.date||''}</small>`}else{review.hidden=true;review.innerHTML=''}}
function submitMission(){const u=current();if(!u||!u.mission?.assigned)return;const text=$('missionSubmission').value.trim();if(!text)return;const list=students(),target=list.find(x=>x.id===u.id);if(!target)return;target.mission=target.mission||{};target.mission.submission={text,date:new Date().toLocaleString('ar-TN')};target.mission.status='submitted';target.mission.progressAwarded=true;target.progress=Math.min(100,(target.progress||0)+20);saveStudents(list);$('missionSubmissionFeedback').textContent='تم إرسال إنجازك إلى الأستاذ. سيظهر له الآن للمراجعة.';showDashboard()}
function showDashboard(){const u=current(); if(!u){$('loginPanel').hidden=false;$('dashboard').hidden=true;return} $('loginPanel').hidden=true;$('dashboard').hidden=false; $('studentName').textContent=u.name; $('profileName').textContent=u.name; $('profileSchool').textContent=u.school; $('profileStatus').textContent=statusLabel(u.status); $('profileStatus').className='status-pill '+u.status; $('profileClass').textContent=u.className||'آداب'; $('researchTool').style.display=(u.status==='active'||u.status==='verified')?'flex':'none'; $('trainingTool').style.display=u.status==='verified'?'flex':'none'; $('missionTitle').textContent=u.mission?.title||'ابدأ ببناء فهمك'; $('missionText').textContent=u.mission?.text||'ابدأ بدرس من المحور الذي تراجعه ثم انتقل إلى التدريب المرتبط به.'; const missionLink=$('missionLink'); if(missionLink){const c=u.mission?.contentId; missionLink.href=c?missionContentPath(c):'lessons__index.html'; missionLink.textContent=c?'فتح المحتوى المرتبط ←':'متابعة المهمة ←'; missionLink.onclick=()=>{if(c)window.location.assign(missionContentPath(c));};} $('messageCount').textContent=(u.messages||[]).filter(m=>m.from==='teacher'&&!m.read).length; $('progressValue').textContent=(u.progress||0)+'%'; $('progressBar').style.width=(u.progress||0)+'%'; renderMessages(u); renderMessageSection(u);renderNotices(u);renderMissionWorkspace(u);}
function renderMessages(u){const box=$('messagesPreview'); const msgs=u.messages||[]; box.innerHTML=msgs.length?msgs.slice(-3).reverse().map(m=>`<div class="message-item ${m.from==='teacher'?'teacher-msg':''}"><b>${m.from==='teacher'?'الأستاذ':'أنت'}</b><span>${m.text}</span><small>${m.read?'مقروءة':'جديدة'}</small></div>`).join(''):'<p class="muted">لا توجد رسائل بعد.</p>'}
$('openLogin').onclick=()=>openModal('login');$('openSignup').onclick=()=>openModal('signup');$('switchSignup').onclick=()=>openModal('signup');$('forgot').onclick=()=>{$('formFeedback').textContent='إذا نسيت كلمة العبور، يمكنك مراسلة الأستاذ من قسم الرسائل داخل فضائك بعد تسجيل الدخول.'};$('openMessages').onclick=e=>{e.preventDefault();document.getElementById('messages').scrollIntoView({behavior:'smooth'});}; modal.querySelectorAll('[data-close]').forEach(x=>x.onclick=close);
$('logout').onclick=()=>{sessionStorage.removeItem(SESSION);sessionStorage.removeItem(CLOUD);CLOUD_STUDENT=null;location.reload()};
$('accountForm').onsubmit=async e=>{e.preventDefault();const phone=$('phoneInput').value.trim(),password=$('passwordInput').value,name=$('nameInput').value.trim(),school=$('schoolInput').value.trim(),feedback=$('formFeedback');feedback.textContent='';if(mode==='signup'){const errors=[];if(name.length<2)errors.push('الاسم واللقب يجب أن يتكوّنا من حرفين على الأقل.');if(school.length<2)errors.push('اسم المعهد يجب أن يتكوّن من حرفين على الأقل.');if(phone.length<6)errors.push('رقم الهاتف يجب أن يحتوي على 6 أرقام أو أكثر.');if(password.length<6)errors.push('كلمة العبور يجب أن تحتوي على 6 أحرف أو أرقام على الأقل.');if(errors.length){feedback.textContent=errors.join(' ');return}}try{const path=mode==='signup'?'/signup':'/login';const payload=mode==='signup'?{name,school,phone,password,class_name:'آداب'}:{phone,password};const d=await cloudJson(path,{method:'POST',body:JSON.stringify(payload)});CLOUD_STUDENT=d.student;localStorage.setItem(KEY,JSON.stringify([CLOUD_STUDENT]));sessionStorage.setItem(CLOUD,d.token);sessionStorage.setItem(SESSION,phone);close();showDashboard();return}catch(err){console.error('[adab-auth]',err);if(IS_PUBLISHED){feedback.textContent=err.message||'تعذر تنفيذ العملية الآن. حاول مرة أخرى.';return}}if(mode==='signup'){let list=students();if(list.some(s=>s.phone===phone)){feedback.textContent='هذا الرقم مرتبط بحساب موجود. جرّب تسجيل الدخول.';return}const u={id:Date.now(),name,school,phone,password,status:'new',className:'آداب',progress:0,messages:[],mission:{title:'ابدأ ببناء فهمك',text:'راجع درسًا واحدًا من المحور الذي تختاره ثم عدّ إلى فضائك.'}};list.push(u);saveStudents(list);sessionStorage.setItem(SESSION,phone);close();showDashboard();return}const u=students().find(s=>s.phone===phone&&s.password===password);if(!u){feedback.textContent='رقم الهاتف أو كلمة العبور غير صحيحة.';return}if(u.status==='suspended'){feedback.textContent='حسابك موقوف حاليًا. تواصل مع الأستاذ.';return}sessionStorage.setItem(SESSION,phone);close();showDashboard()};
function renderMessageSection(u){const box=$('studentMessagesList'),count=$('messageSectionCount'); if(!box||!count)return; const msgs=u.messages||[]; count.textContent=msgs.filter(m=>m.from==='teacher'&&!m.read).length; box.innerHTML=msgs.length?msgs.slice().reverse().map(m=>`<div class="message-item ${m.from==='teacher'?'teacher-msg':''}"><div><b>${m.from==='teacher'?'الأستاذ':'أنت'}</b><small>${m.date||''}</small></div><p>${m.text}</p><span>${m.read?'مقروءة':'جديدة'}</span></div>`).join(''):'<p class="muted">لا توجد رسائل بعد. يمكنك إرسال رسالتك الأولى إلى الأستاذ.</p>';}
$('missionSubmissionForm').onsubmit=e=>{e.preventDefault();submitMission()};
$('studentMessageForm').onsubmit=e=>{e.preventDefault();const u=current();if(!u)return;const text=$('studentMessageInput').value.trim();if(!text)return;let list=students(),target=list.find(s=>s.id===u.id);if(!target)return;target.messages=target.messages||[];target.messages.push({from:'student',text,read:false,date:new Date().toLocaleString('ar-TN')});saveStudents(list);$('studentMessageInput').value='';$('studentMessageFeedback').textContent='تم إرسال رسالتك إلى الأستاذ.';showDashboard();setTimeout(()=>{$('studentMessageFeedback').textContent='';},2500);};
$('markProgress').onclick=()=>{const list=students(),u=current();if(!u)return;u.progress=Math.min(100,(u.progress||0)+10);saveStudents(list);showDashboard()};
showDashboard();
if(sessionStorage.getItem(CLOUD)){hydrateCloud().then(ok=>{if(ok)showDashboard()})}

/* ===== اختبارات قصيرة وملاحظات الأستاذ ===== */
const TESTS='adab_tests_demo_v2', NOTES='adab_notes_demo_v2';
const readDemo=k=>JSON.parse(localStorage.getItem(k)||'[]'); const writeDemo=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
function renderStudentTests(u){const box=$('studentTestList');if(!box)return;const arr=readDemo(TESTS).filter(t=>t.published&&(!t.studentId||String(t.studentId)===String(u.id)));$('studentTestCount').textContent=arr.length;box.innerHTML=arr.length?arr.map(t=>{const mine=(t.results||[]).find(r=>String(r.studentId)===String(u.id));return `<div class="admin-test-row"><div><span class="notice-kind">${t.axisLabel}</span><b>${t.title}</b><p>${t.instructions}</p><small>${t.questions.length} أسئلة</small>${mine?`<div class="mission-feedback"><strong>أرسلت إجابتك</strong><small>${mine.date||''}</small></div>`:`<form class="student-test-form" data-id="${t.id}">${t.questions.map((q,i)=>`<div class="test-question"><b>س${i+1}. ${q}</b><textarea class="test-answer" data-q="${i}" required placeholder="اكتب إجابتك..."></textarea></div>`).join('')}<button class="primary-btn" type="submit">إرسال الاختبار</button><div class="form-feedback"></div></form>`}</div></div>`}).join(''):'<div class="empty-state">لا توجد اختبارات منشورة لك حاليًا.</div>';box.querySelectorAll('.student-test-form').forEach(f=>f.onsubmit=e=>{e.preventDefault();const id=f.dataset.id,answers=[...f.querySelectorAll('.test-answer')].map(x=>x.value.trim());if(answers.some(x=>!x)){f.querySelector('.form-feedback').textContent='أكمل الإجابات قبل الإرسال.';return}const a=readDemo(TESTS),t=a.find(x=>String(x.id)===id);if(!t)return;t.results=t.results||[];t.results=t.results.filter(r=>String(r.studentId)!==String(u.id));t.results.push({studentId:u.id,studentName:u.name,answers,date:new Date().toLocaleString('ar-TN')});writeDemo(TESTS,a);f.querySelector('.form-feedback').textContent='تم إرسال الاختبار إلى الأستاذ.';renderStudentTests(u)})}
function renderStudentNotes(u){const box=$('studentNotesList');if(!box)return;const arr=readDemo(NOTES).filter(n=>String(n.studentId)===String(u.id));box.innerHTML=arr.length?arr.slice().reverse().map(n=>{const label=({strength:'نقطة قوة',support:'ما يحتاج إلى دعم',next:'الخطوة التالية',general:'ملاحظة عامة'})[n.type]||'ملاحظة';return `<div class="admin-note-row"><span class="note-chip">${label}</span>${n.contextTitle?`<span class="muted">مرتبطة بـ: ${n.contextTitle}</span>`:''}<p>${n.text}</p><small>${n.date||''}</small>${n.reply?`<div class="mission-feedback"><strong>ردّك:</strong><p>${n.reply.text}</p><small>${n.reply.date||''}</small></div>`:`<form class="note-reply-form" data-note="${n.id}"><textarea rows="2" placeholder="يمكنك الرد على ملاحظة الأستاذ..." required></textarea><button class="ghost-btn" type="submit">إرسال الرد</button><div class="form-feedback"></div></form>`}</div>`}).join(''):'<div class="empty-state">ستظهر هنا ملاحظات الأستاذ وتغذيته الراجعة.</div>';box.querySelectorAll('.note-reply-form').forEach(f=>f.onsubmit=e=>{e.preventDefault();const text=f.querySelector('textarea').value.trim();if(!text)return;const a=readDemo(NOTES),n=a.find(x=>String(x.id)===String(f.dataset.note));if(!n)return;n.reply={text,date:new Date().toLocaleString('ar-TN')};writeDemo(NOTES,a);renderStudentNotes(u)})}
const _showDashboardExpanded=showDashboard; showDashboard=function(){_showDashboardExpanded();const u=current();if(u){renderStudentTests(u);renderStudentNotes(u)}};
if(typeof sessionStorage!=='undefined'&&sessionStorage.getItem(SESSION)){setTimeout(()=>showDashboard(),0)}

/* ===== 2.0 CLOUD BRIDGE: shared student state ===== */
let CLOUD_STATE={messages:[],missions:[],tests:[],notes:[],announcements:[],progress:[],content:[]};
function studentHasCloud(){return !!sessionStorage.getItem(CLOUD)}
function localMissionToCloud(m){return m}
async function refreshStudentCloud(){
  if(!studentHasCloud())return false;
  try{
    const [me,msg,mis,tests,notes,ann,prog,content]=await Promise.all([
      cloudJson('/me'),cloudJson('/student/messages'),cloudJson('/student/missions'),cloudJson('/student/tests'),cloudJson('/student/notes'),cloudJson('/student/announcements'),cloudJson('/student/progress'),cloudJson('/content')
    ]);
    CLOUD_STUDENT=me.student;
    CLOUD_STATE={messages:msg.messages||[],missions:mis.missions||[],tests:tests.tests||[],notes:notes.notes||[],announcements:ann.announcements||[],progress:prog.progress||[],content:content.items||[]};
    const latest=CLOUD_STATE.missions[0];
    if(latest){CLOUD_STUDENT.mission={assigned:true,title:latest.title,text:latest.instructions,contentId:latest.content_id,status:latest.status,missionId:latest.id,submission:latest.submission_text?{text:latest.submission_text,date:latest.submitted_at}:null,review:latest.feedback?{feedback:latest.feedback,date:latest.reviewed_at}:null};}
    CLOUD_STUDENT.messages=CLOUD_STATE.messages.map(m=>({id:m.id,from:m.sender_type==='teacher'?'teacher':'student',text:m.body,read:!!m.is_read,date:m.created_at}));
    localStorage.setItem(KEY,JSON.stringify([CLOUD_STUDENT])); sessionStorage.setItem(SESSION,CLOUD_STUDENT.phone);
    return true;
  }catch(e){return false}
}
function cloudMission(){return CLOUD_STATE.missions[0]||null}
function cloudContentHref(c){if(!c)return 'lessons__index.html'; return c.source_url?('/'+String(c.source_url).replace(/^\//,'')):'/content/'+encodeURIComponent(c.id)}
async function submitMission(){
  const u=current(),m=cloudMission(); if(studentHasCloud()){
    if(!u||!m)return;
    const text=$('missionSubmission')?.value.trim(); if(!text)return;
    try{await cloudJson('/student/missions/'+encodeURIComponent(m.id)+'/submit',{method:'POST',body:JSON.stringify({submission_text:text})}); $('missionSubmissionFeedback').textContent='تم إرسال إنجازك إلى الأستاذ.'; await refreshStudentCloud(); showDashboard(); return;}catch(e){$('missionSubmissionFeedback').textContent='تعذر الإرسال الآن. حاول مرة أخرى.';return}
  }
  const list=students(),target=list.find(x=>String(x.id)===String(u?.id));if(!target)return;const text=$('missionSubmission')?.value.trim();if(!text)return;target.mission=target.mission||{};target.mission.submission={text,date:new Date().toLocaleString('ar-TN')};target.mission.status='submitted';target.mission.progressAwarded=true;target.progress=Math.min(100,(target.progress||0)+20);saveStudents(list);$('missionSubmissionFeedback').textContent='تم إرسال إنجازك إلى الأستاذ.';showDashboard();
}
function renderCloudMessages(u){const msgs=CLOUD_STATE.messages||[];const preview=$('messagesPreview'),box=$('studentMessagesList'),count=$('messageSectionCount'),top=$('messageCount');const unread=msgs.filter(m=>m.sender_type==='teacher'&&!m.is_read).length;if(top)top.textContent=unread;if(count)count.textContent=unread;if(preview)preview.innerHTML=msgs.length?msgs.slice(0,3).map(m=>`<div class="message-item ${m.sender_type==='teacher'?'teacher-msg':''}"><b>${m.sender_type==='teacher'?'الأستاذ':'أنت'}</b><span>${m.body}</span><small>${m.is_read?'مقروءة':'جديدة'}</small></div>`).join(''):'<p class="muted">لا توجد رسائل بعد.</p>';if(box)box.innerHTML=msgs.length?msgs.map(m=>`<div class="message-item ${m.sender_type==='teacher'?'teacher-msg':''}"><div><b>${m.sender_type==='teacher'?'الأستاذ':'أنت'}</b><small>${m.created_at||''}</small></div><p>${m.body}</p><span>${m.is_read?'مقروءة':'جديدة'}</span></div>`).join(''):'<p class="muted">لا توجد رسائل بعد. يمكنك إرسال رسالتك الأولى إلى الأستاذ.</p>'}
function renderCloudMission(u){const m=cloudMission();const linked=CLOUD_STATE.content?.find?.(x=>String(x.id)===String(m?.content_id));const local={assigned:!!m,title:m?.title,text:m?.instructions,contentId:m?.content_id,status:m?.status,submission:m?.submission_text?{text:m.submission_text,date:m.submitted_at}:null,review:m?.feedback?{feedback:m.feedback,date:m.reviewed_at}:null};renderMissionWorkspace({...u,mission:m?local:{}});const link=$('workspaceContentLink');if(link&&linked)link.href=cloudContentHref(linked)}
function renderCloudTests(u){const box=$('studentTestList');if(!box)return;const arr=CLOUD_STATE.tests||[];$('studentTestCount').textContent=arr.length;box.innerHTML=arr.length?arr.map(t=>{const answers=Object.fromEntries((t.answers||[]).map(a=>[a.question_id,a]));const done=(t.questions||[]).length>0&&(t.questions||[]).every(q=>answers[q.id]);return `<div class="admin-test-row"><div><span class="notice-kind">${['','شعر الحماسة','المنزع العقلي','رسالة الغفران','مغامرة رأس المملوك جابر','حدث أبو هريرة قال'][t.axis_no]||'اختبار'}</span><b>${t.title}</b><p>${t.description||'اختبار تقويمي قصير.'}</p><small>${(t.questions||[]).length} أسئلة</small>${done?`<div class="mission-feedback"><strong>أرسلت إجاباتك</strong></div>`:`<form class="student-test-form" data-id="${t.id}">${(t.questions||[]).map((q,i)=>`<div class="test-question"><b>س${i+1}. ${q.prompt}</b><textarea class="test-answer" data-qid="${q.id}" required placeholder="اكتب إجابتك..."></textarea></div>`).join('')}<button class="primary-btn" type="submit">إرسال الاختبار</button><div class="form-feedback"></div></form>`}</div></div>`}).join(''):'<div class="empty-state">لا توجد اختبارات منشورة لك حاليًا.</div>';box.querySelectorAll('.student-test-form').forEach(f=>f.onsubmit=async e=>{e.preventDefault();const t=arr.find(x=>String(x.id)===String(f.dataset.id));if(!t)return;const fields=[...f.querySelectorAll('.test-answer')];if(fields.some(x=>!x.value.trim())){f.querySelector('.form-feedback').textContent='أكمل الإجابات قبل الإرسال.';return}try{for(const x of fields)await cloudJson('/student/answers',{method:'POST',body:JSON.stringify({test_id:t.id,question_id:x.dataset.qid,answer_text:x.value.trim()})});f.querySelector('.form-feedback').textContent='تم إرسال الاختبار إلى الأستاذ.';await refreshStudentCloud();renderCloudTests(CLOUD_STUDENT)}catch(err){f.querySelector('.form-feedback').textContent='تعذر إرسال الاختبار الآن.'}})}
function renderCloudNotes(){const box=$('studentNotesList');if(!box)return;const arr=CLOUD_STATE.notes||[];box.innerHTML=arr.length?arr.map(n=>{const label=({strength:'نقطة قوة',support:'ما يحتاج إلى دعم',next:'الخطوة التالية',general:'ملاحظة عامة'})[n.note_type]||'ملاحظة';return `<div class="admin-note-row"><span class="note-chip">${label}</span>${n.linked_content_id?`<span class="muted">مرتبطة بالمحتوى</span>`:''}<p>${n.note_text}</p><small>${n.created_at||''}</small>${n.student_reply?`<div class="mission-feedback"><strong>ردّك:</strong><p>${n.student_reply}</p><small>${n.replied_at||''}</small></div>`:`<form class="note-reply-form" data-note="${n.id}"><textarea rows="2" placeholder="يمكنك الرد على ملاحظة الأستاذ..." required></textarea><button class="ghost-btn" type="submit">إرسال الرد</button><div class="form-feedback"></div></form>`}</div>`}).join(''):'<div class="empty-state">ستظهر هنا ملاحظات الأستاذ وتغذيته الراجعة.</div>';box.querySelectorAll('.note-reply-form').forEach(f=>f.onsubmit=async e=>{e.preventDefault();const text=f.querySelector('textarea').value.trim();if(!text)return;try{await cloudJson('/student/notes/'+encodeURIComponent(f.dataset.note)+'/reply',{method:'POST',body:JSON.stringify({student_reply:text})});await refreshStudentCloud();renderCloudNotes()}catch(err){f.querySelector('.form-feedback').textContent='تعذر إرسال الرد الآن.'}})}
function renderCloudAnnouncements(){const u=current(),box=$('studentNoticeList');if(!box)return;const arr=CLOUD_STATE.announcements||[];box.innerHTML=arr.length?arr.slice(0,6).map(n=>`<div class="student-notice-item"><b>${n.kind||'تنبيه'}</b><h3>${n.title}</h3><p>${n.body}</p><small>${n.created_at||''}</small>${n.linked_content_id?`<a href="/content/${encodeURIComponent(n.linked_content_id)}">فتح المحتوى ←</a>`:''}</div>`).join(''):'<div class="muted">لا توجد إعلانات جديدة.</div>'}
async function cloudStudentMarkProgress(){if(!studentHasCloud()){const list=students(),u=current();if(!u)return;u.progress=Math.min(100,(u.progress||0)+10);saveStudents(list);showDashboard();return}try{const d=await cloudJson('/student/progress/overall',{method:'POST',body:JSON.stringify({increment:10})});CLOUD_STUDENT.progress=d.progress;await refreshStudentCloud();showDashboard()}catch(e){}}
$('missionSubmissionForm').onsubmit=e=>{e.preventDefault();submitMission()};
$('studentMessageForm').onsubmit=async e=>{e.preventDefault();const u=current(),text=$('studentMessageInput')?.value.trim();if(!u||!text)return;if(studentHasCloud()){try{await cloudJson('/student/messages',{method:'POST',body:JSON.stringify({body:text,linked_mission_id:cloudMission()?.id||null})});$('studentMessageInput').value='';$('studentMessageFeedback').textContent='تم إرسال رسالتك إلى الأستاذ.';await refreshStudentCloud();showDashboard();setTimeout(()=>{$('studentMessageFeedback').textContent=''},2500)}catch(err){$('studentMessageFeedback').textContent='تعذر إرسال الرسالة الآن.'}return}let list=students(),target=list.find(s=>String(s.id)===String(u.id));if(!target)return;target.messages=target.messages||[];target.messages.push({from:'student',text,read:false,date:new Date().toLocaleString('ar-TN')});saveStudents(list);$('studentMessageInput').value='';showDashboard()};
$('markProgress').onclick=cloudStudentMarkProgress;
const _show20=showDashboard; showDashboard=function(){_show20();const u=current();if(studentHasCloud()&&u){renderCloudMessages(u);renderCloudMission(u);renderCloudTests(u);renderCloudNotes();renderCloudAnnouncements()}};
if(studentHasCloud())setTimeout(async()=>{if(await refreshStudentCloud())showDashboard()},0);

/* 2.0: cloud-auth form replaces the local-first handler while retaining offline fallback. */
$('accountForm').onsubmit=async e=>{
  e.preventDefault();
  const phone=$('phoneInput').value.trim(),password=$('passwordInput').value,name=$('nameInput').value.trim(),school=$('schoolInput').value.trim();
  if(mode==='signup' && (!name||!school||!phone||!password)){$('formFeedback').textContent='يرجى استكمال جميع البيانات.';return}
  try{
    const path=mode==='signup'?'/signup':'/login';
    const payload=mode==='signup'?{name,school,phone,password,class_name:'آداب'}:{phone,password};
    const d=await cloudJson(path,{method:'POST',body:JSON.stringify(payload)});
    CLOUD_STUDENT=d.student;sessionStorage.setItem(CLOUD,d.token);sessionStorage.setItem(SESSION,d.student.phone);localStorage.setItem(KEY,JSON.stringify([d.student]));
    close();await refreshStudentCloud();showDashboard();return;
  }catch(err){
    if(mode==='signup'){
      const list=students();if(list.some(s=>s.phone===phone)){$('formFeedback').textContent='هذا الرقم مرتبط بحساب موجود. جرّب تسجيل الدخول.';return}
      const u={id:Date.now(),name,school,phone,password,status:'new',className:'آداب',progress:0,messages:[],mission:{title:'ابدأ ببناء فهمك',text:'راجع درسًا واحدًا من المحور الذي تختاره ثم عدّ إلى فضائك.'}};list.push(u);saveStudents(list);sessionStorage.setItem(SESSION,phone);close();showDashboard();return;
    }
    const u=students().find(s=>s.phone===phone&&s.password===password);if(!u){$('formFeedback').textContent='رقم الهاتف أو كلمة العبور غير صحيحة.';return}if(u.status==='suspended'){$('formFeedback').textContent='حسابك موقوف حاليًا. تواصل مع الأستاذ.';return}sessionStorage.setItem(SESSION,phone);close();showDashboard();
  }
};
